-- =============================================================
-- Full schema migration for staging Supabase project
-- Apply this in: Supabase dashboard → SQL editor (staging project)
-- =============================================================

-- SEQUENCES
CREATE SEQUENCE IF NOT EXISTS public.categories_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.clients_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.order_items_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.orders_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.products_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.sizes_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.units_id_seq;

-- TABLES (dependency order)

CREATE TABLE IF NOT EXISTS public.units (
  id integer NOT NULL DEFAULT nextval('public.units_id_seq'::regclass),
  name character varying,
  CONSTRAINT "pk_Unit" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sizes (
  id integer NOT NULL DEFAULT nextval('public.sizes_id_seq'::regclass),
  name character varying,
  CONSTRAINT "pk_Sizes" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories (
  id integer NOT NULL DEFAULT nextval('public.categories_id_seq'::regclass),
  name character varying,
  CONSTRAINT "pk_Categories" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.client_type (
  id integer NOT NULL,
  name character varying,
  CONSTRAINT "pk_CustomerType" PRIMARY KEY (id),
  CONSTRAINT "uc_CustomerType_Name" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL DEFAULT auth.uid(),
  name text,
  email text NOT NULL DEFAULT ''::text,
  role text NOT NULL DEFAULT '''user'''::text,
  approved boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_email_key UNIQUE (email),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.admin_users (
  id uuid NOT NULL,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id),
  CONSTRAINT admin_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.clients (
  id integer NOT NULL DEFAULT nextval('public.clients_id_seq'::regclass),
  type integer NOT NULL,
  name character varying NOT NULL CHECK (length(name::text) > 0),
  address character varying,
  other_details character varying,
  delivery_address text,
  code character varying,
  tva boolean DEFAULT false,
  CONSTRAINT "pk_Customer" PRIMARY KEY (id),
  CONSTRAINT clients_code_key UNIQUE (code),
  CONSTRAINT "fk_Customer_Type" FOREIGN KEY (type) REFERENCES public.client_type(id)
);

CREATE TABLE IF NOT EXISTS public.products (
  id integer NOT NULL DEFAULT nextval('public.products_id_seq'::regclass),
  name text,
  unit_id integer NOT NULL,
  size_id integer,
  width numeric,
  length numeric,
  m2_brut double precision,
  piece_per_pack smallint,
  m2_util double precision,
  thickness double precision,
  CONSTRAINT "pk_Product" PRIMARY KEY (id),
  CONSTRAINT products_name_key UNIQUE (name),
  CONSTRAINT "fk_Product_UnitID" FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT "fk_Product_SizeID" FOREIGN KEY (size_id) REFERENCES public.sizes(id)
);

CREATE TABLE IF NOT EXISTS public.orders (
  id integer NOT NULL DEFAULT nextval('public.orders_id_seq'::regclass),
  client_id integer NOT NULL,
  operator_id uuid,
  deleted_at timestamp with time zone,
  delivery_address text,
  expected_delivery date,
  date_order_delivered date,
  total_amount numeric,
  total_amount_final numeric,
  comment text,
  voucher text,
  date_order_placed timestamp with time zone DEFAULT timezone('UTC'::text, now()),
  until_delivery_date boolean DEFAULT false,
  for_first_hour boolean DEFAULT false,
  total_quantity numeric DEFAULT '0'::numeric,
  paid_amount numeric DEFAULT '0'::numeric,
  just_offer boolean DEFAULT false,
  sort_order numeric,
  delivery_fee numeric DEFAULT '0'::numeric,
  CONSTRAINT "pk_Order" PRIMARY KEY (id),
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT orders_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.profiles(id)
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id integer NOT NULL DEFAULT nextval('public.order_items_id_seq'::regclass),
  product_id integer NOT NULL,
  order_id integer NOT NULL,
  category_id integer,
  price numeric,
  packs_pieces text,
  item_status boolean DEFAULT false,
  quantity numeric NOT NULL,
  CONSTRAINT "pk_OrderItem" PRIMARY KEY (id),
  CONSTRAINT "fk_OrderItem_ProductID" FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT "fk_OrderItem_OrderID" FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

CREATE TABLE IF NOT EXISTS public.stocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  stock numeric NOT NULL,
  booked_stock numeric DEFAULT '0'::numeric,
  CONSTRAINT stocks_product_id_key UNIQUE (product_id),
  CONSTRAINT stocks_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.prices_new (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id integer NOT NULL,
  category_id integer NOT NULL,
  price numeric NOT NULL,
  size_id integer,
  product_id integer,
  CONSTRAINT prices_new_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id),
  CONSTRAINT prices_new_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT prices_new_size_id_fkey FOREIGN KEY (size_id) REFERENCES public.sizes(id),
  CONSTRAINT prices_new_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);

CREATE TABLE IF NOT EXISTS public.coming_wares (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expected_delivery date,
  comment text,
  total_quantity numeric,
  name text,
  all_for_order boolean DEFAULT false,
  verified boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.coming_wares_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  product_id integer NOT NULL,
  category integer NOT NULL,
  quantity numeric NOT NULL,
  is_correct boolean,
  comment text,
  for_order boolean DEFAULT false,
  CONSTRAINT coming_wares_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.coming_wares(id),
  CONSTRAINT coming_wares_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT coming_wares_items_category_fkey FOREIGN KEY (category) REFERENCES public.categories(id)
);

CREATE TABLE IF NOT EXISTS public.client_phones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer,
  phone character varying,
  label text,
  CONSTRAINT client_phones_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);

-- EXTRA INDEXES
CREATE INDEX IF NOT EXISTS "idx_Customer_Name" ON public.clients USING btree (name);

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_phones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coming_wares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coming_wares_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prices_new ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sizes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES
CREATE POLICY "Enable access for all users" ON public.admin_users FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.categories FOR ALL TO public USING (true);
CREATE POLICY "Allow acces to users" ON public.client_phones FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.client_type FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.clients FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.coming_wares FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.coming_wares_items FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.order_items FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.orders FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.prices_new FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.products FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.sizes FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.stocks FOR ALL TO public USING (true);
CREATE POLICY "Enable access for all users" ON public.units FOR ALL TO public USING (true);

-- profiles has fine-grained policies
CREATE POLICY "Admin can delete user" ON public.profiles FOR DELETE TO public
  USING (EXISTS (SELECT 1 FROM admin_users WHERE admin_users.id = auth.uid()));
CREATE POLICY "Admin can view all profiles" ON public.profiles FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM admin_users WHERE admin_users.id = auth.uid()));
CREATE POLICY "Admins can update any profile" ON public.profiles FOR UPDATE TO public
  USING (EXISTS (SELECT 1 FROM admin_users WHERE admin_users.id = auth.uid()));
CREATE POLICY "Allow only approved users" ON public.profiles FOR SELECT TO public
  USING (approved = true);
CREATE POLICY "Allow user to read their own profile" ON public.profiles FOR SELECT TO public
  USING (auth.uid() = id);
CREATE POLICY "Enable insert for users based on user_id" ON public.profiles FOR INSERT TO public
  WITH CHECK ((SELECT auth.uid()) = id);

-- FUNCTIONS
CREATE OR REPLACE FUNCTION public.add_to_product_stock(p_product_id bigint, p_amount integer)
RETURNS boolean LANGUAGE plpgsql AS $function$
begin
  update stocks set stock = stock + p_amount where product_id = p_product_id;
  if found then return true; else return false; end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.product_booked_stock_sold(p_product_id bigint, p_amount integer)
RETURNS boolean LANGUAGE plpgsql AS $function$
begin
  update stocks set stock = stock - p_amount, booked_stock = booked_stock - p_amount
  where product_id = p_product_id;
  if found then return true; else return false; end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.assign_default_sort_order()
RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.sort_order IS NULL THEN
    NEW.sort_order := COALESCE((SELECT MAX(sort_order) FROM orders) + 1, 1);
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_order_sort_orders(items jsonb)
RETURNS void LANGUAGE sql AS $function$
  update orders o set sort_order = i.sort_order
  from jsonb_to_recordset(items) as i(id int, sort_order int)
  where o.id = i.id;
$function$;

CREATE OR REPLACE FUNCTION public.trg_order_item_book_stock()
RETURNS trigger LANGUAGE plpgsql AS $function$
declare v_unit_id integer; v_just_offer boolean;
begin
  select just_offer into v_just_offer from orders where id = new.order_id;
  if v_just_offer = true then return new; end if;
  select unit_id into v_unit_id from products where id = new.product_id;
  if v_unit_id is not null and v_unit_id != 2 then
    update stocks set booked_stock = booked_stock + new.quantity where product_id = new.product_id;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.trg_order_item_delete_unbook()
RETURNS trigger LANGUAGE plpgsql AS $function$
declare v_unit_id integer; v_just_offer boolean;
begin
  if old.item_status = false then
    select just_offer into v_just_offer from orders where id = old.order_id;
    if v_just_offer = true then return old; end if;
    select unit_id into v_unit_id from products where id = old.product_id;
    if v_unit_id is not null and v_unit_id != 2 then
      update stocks set booked_stock = booked_stock - old.quantity where product_id = old.product_id;
      if not found then raise exception 'No stock row for product_id %', old.product_id; end if;
    end if;
  end if;
  return old;
end;
$function$;

CREATE OR REPLACE FUNCTION public.trg_order_item_status_change()
RETURNS trigger LANGUAGE plpgsql AS $function$
declare v_unit_id integer; v_just_offer boolean;
begin
  if old.item_status is distinct from new.item_status then
    select just_offer into v_just_offer from orders where id = new.order_id;
    if v_just_offer = true then return new; end if;
    select unit_id into v_unit_id from products where id = new.product_id;
    if v_unit_id is not null and v_unit_id != 2 then
      if old.item_status = false and new.item_status = true then
        update stocks set booked_stock = booked_stock - new.quantity, stock = stock - new.quantity
        where product_id = new.product_id;
      elsif old.item_status = true and new.item_status = false then
        update stocks set booked_stock = booked_stock + new.quantity, stock = stock + new.quantity
        where product_id = new.product_id;
      end if;
    end if;
  end if;
  return new;
end;
$function$;

-- TRIGGERS
CREATE TRIGGER order_items_after_insert_book_stock
  AFTER INSERT ON public.order_items FOR EACH ROW
  EXECUTE FUNCTION trg_order_item_book_stock();

CREATE TRIGGER order_items_after_delete_unbook
  AFTER DELETE ON public.order_items FOR EACH ROW
  EXECUTE FUNCTION trg_order_item_delete_unbook();

CREATE TRIGGER order_items_after_status_update
  AFTER UPDATE ON public.order_items FOR EACH ROW
  EXECUTE FUNCTION trg_order_item_status_change();
